### ISSUE TITLE
脚本运行正常，但是通过opkg安装的包重启后会丢

### ISSUE THREAD

**Issue by JimiZhou** [zhaxingyu/xiaomi_be6500pro#2]
请问6500PRO这个重启清空的设定是否有办法关闭？
目前我的环境上是通过opkg安装并配置了tailscale，但是重启后/etc/init.d/tailscale启动脚本和/etc/config/tailscale配置都丢失了。

**Comment by oaooi** [comment]
可以考虑保存到别的地方，然后用文件软链的方式实现，然后创建一个脚本加入到防火墙规则（这个不会丢失），每次开机自动软链过去

**Comment by JimiZhou** [comment]
嗯嗯，感谢回复，目前我也是这么修改的，只是好奇清空的逻辑在哪块，之前AX3600解锁ssh之后装的包不会丢失

**Comment by oaooi** [comment]
固件设置，除非改固件吧

**Comment by oaooi** [comment]
照理overlay挂载后etc config应该不会丢，不过也记不清了

**Comment by JimiZhou** [comment]
好的，不想刷第三方固件目前就先这样配置了，感谢
